[package]
name = "pretty-table-explorer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pte"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = { version = "0.28", features = ["use-dev-tty"] }
postgres = "0.19"
ratatui = "0.29"
